# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва для ідентифікації цієї конфігурації', max_length=200, verbose_name='Назва конфігурації')),
                ('sheet_url', models.URLField(verbose_name='URL Google таблиці')),
                ('sheet_id', models.CharField(help_text='ID Google таблиці (автоматично витягується з URL)', max_length=100, verbose_name='ID таблиці')),
                ('sheet_name', models.CharField(default='Sheet1', help_text='Назва сторінки/вкладки в Google таблиці (наприклад: \'Sheet1\', \'Прайс\', \'Ціни\')', max_length=100, verbose_name='Назва сторінки')),
                ('is_active', models.BooleanField(default=True, help_text='Чи використовувати цю конфігурацію', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Конфігурація Google таблиці',
                'verbose_name_plural': 'Конфігурації Google таблиць',
                'db_table': 'price_parser_google_sheet_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успішно'), ('error', 'Помилка'), ('partial', 'Частково')], max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Час початку')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Час завершення')),
                ('items_processed', models.PositiveIntegerField(default=0, verbose_name='Оброблено товарів')),
                ('items_updated', models.PositiveIntegerField(default=0, verbose_name='Оновлено товарів')),
                ('errors', models.JSONField(default=list, help_text='Список помилок під час оновлення', verbose_name='Помилки')),
                ('log_details', models.TextField(blank=True, verbose_name='Деталі логу')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='price_parser.googlesheetconfig', verbose_name='Конфігурація')),
            ],
            options={
                'verbose_name': 'Лог оновлення цін',
                'verbose_name_plural': 'Логи оновлення цін',
                'db_table': 'price_parser_update_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FurniturePriceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(help_text='Назва меблів як вона вказана в Google таблиці', max_length=200, verbose_name='Назва в таблиці')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_mappings', to='price_parser.googlesheetconfig', verbose_name='Конфігурація')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_mappings', to='furniture.furniture', verbose_name='Меблі в БД')),
            ],
            options={
                'verbose_name': "Зв'язок назв меблів",
                'verbose_name_plural': "Зв'язки назв меблів",
                'db_table': 'price_parser_furniture_mapping',
                'ordering': ['sheet_name'],
                'unique_together': {('sheet_name', 'config')},
            },
        ),
        migrations.CreateModel(
            name='FurniturePriceCellMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.PositiveIntegerField(help_text='Номер рядка в Google таблиці (наприклад: 5)', verbose_name='Рядок в таблиці')),
                ('sheet_column', models.CharField(help_text='Колонка в Google таблиці (наприклад: E, F, G)', max_length=10, verbose_name='Колонка в таблиці')),
                ('price_type', models.CharField(help_text='Опис типу ціни (наприклад: \'Стільниця стандарт\', \'HPL покриття\')', max_length=100, verbose_name='Тип ціни')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cell_mappings', to='price_parser.googlesheetconfig', verbose_name='Конфігурація Google таблиці')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cell_mappings', to='furniture.furniture', verbose_name='Меблі')),
                ('size_variant', models.ForeignKey(blank=True, help_text='Розмірний варіант для цієї ціни (опціонально)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_cell_mappings', to='furniture.furnituresizevariant', verbose_name='Розмірний варіант')),
            ],
            options={
                'verbose_name': "Зв'язок меблів з коміркою ціни",
                'verbose_name_plural': "Зв'язки меблів з комірками цін",
                'db_table': 'price_parser_furniture_price_cell_mapping',
                'ordering': ['furniture__name', 'sheet_row', 'sheet_column'],
                'unique_together': {('furniture', 'config', 'sheet_row', 'sheet_column')},
            },
        ),
    ]
