# Generated by Django 5.2 on 2025-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0002_furniturepricecellmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlesheetconfig",
            name="sheet_url",
            field=models.URLField(
                help_text="Посилання на Google таблицю",
                verbose_name="URL Google таблиці",
            ),
        ),
    ]
