# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_parser', '0003_alter_googlesheetconfig_sheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheetconfig',
            name='sheet_name',
            field=models.CharField(
                default='Sheet1',
                help_text='Назва сторінки/вкладки в Google таблиці (наприклад: \'Sheet1\', \'Прайс\', \'Ціни\')',
                max_length=100,
                verbose_name='Назва сторінки'
            ),
        ),
    ] 