# Generated by Django 5.2 on 2025-08-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0004_add_sheet_name_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googlesheetconfig",
            name="sheet_name",
        ),
    ]
