# Generated by Django 5.2 on 2025-08-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0005_add_sheet_name_field_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesheetconfig",
            name="sheet_name",
            field=models.CharField(
                default="Sheet1",
                help_text="Назва сторінки/вкладки в Google таблиці (наприклад: 'Sheet1', 'Прайс', 'Ціни')",
                max_length=100,
                verbose_name="Назва сторінки",
            ),
        ),
    ]
