# Generated by Django 5.2 on 2025-08-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0006_googlesheetconfig_sheet_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesheetconfig",
            name="sheet_gid",
            field=models.CharField(
                blank=True,
                help_text="GID сторінки (знаходиться в URL після #gid=). Якщо не вказано, буде використовуватися перша сторінка (gid=0)",
                max_length=20,
                null=True,
                verbose_name="GID сторінки",
            ),
        ),
    ]
