# Generated by Django 5.2 on 2025-08-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0007_googlesheetconfig_sheet_gid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FurniturePriceCellMapping",
        ),
    ]
