# Generated by Django 5.2 on 2025-08-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0008_remove_furniture_price_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesheetconfig",
            name="xlsx_file",
            field=models.FileField(
                blank=True,
                help_text="Завантажте XLSX файл з цінами (альтернатива Google таблиці)",
                null=True,
                upload_to="price_sheets/",
                verbose_name="XLSX файл",
            ),
        ),
        migrations.AlterField(
            model_name="googlesheetconfig",
            name="sheet_id",
            field=models.CharField(
                blank=True,
                help_text="ID Google таблиці (автоматично витягується з URL) або назва XLSX файлу",
                max_length=100,
                null=True,
                verbose_name="ID таблиці",
            ),
        ),
        migrations.AlterField(
            model_name="googlesheetconfig",
            name="sheet_url",
            field=models.URLField(
                blank=True,
                help_text="Посилання на Google таблицю (залиште порожнім для XLSX файлів)",
                null=True,
                verbose_name="URL Google таблиці",
            ),
        ),
    ]
