# Generated by Django 5.2 on 2025-08-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0009_googlesheetconfig_xlsx_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesheetconfig",
            name="price_multiplier",
            field=models.DecimalField(
                decimal_places=4,
                default=1.0,
                help_text="Множник для конвертації цін (наприклад: 1.0 для UAH, 38.5 для USD->UAH)",
                max_digits=10,
                verbose_name="Множник ціни",
            ),
        ),
    ]
