# Generated by Django 5.2 on 2025-09-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0017_furnituresizevariant_is_promotional_and_more"),
        ("price_parser", "0010_add_price_multiplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurniturePriceCellMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_row",
                    models.PositiveIntegerField(
                        help_text="Номер рядка в Google таблиці (наприклад: 5)",
                        verbose_name="Рядок в таблиці",
                    ),
                ),
                (
                    "sheet_column",
                    models.CharField(
                        help_text="Колонка в Google таблиці (наприклад: E, F, G)",
                        max_length=10,
                        verbose_name="Колонка в таблиці",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        help_text="Опис типу ціни (наприклад: 'Стільниця стандарт', 'HPL покриття')",
                        max_length=100,
                        verbose_name="Тип ціни",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активне"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_cell_mappings",
                        to="price_parser.googlesheetconfig",
                        verbose_name="Конфігурація Google таблиці",
                    ),
                ),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_cell_mappings",
                        to="furniture.furniture",
                        verbose_name="Меблі",
                    ),
                ),
                (
                    "size_variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Розмірний варіант для цієї ціни (опціонально)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_cell_mappings",
                        to="furniture.furnituresizevariant",
                        verbose_name="Розмірний варіант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зв'язок меблів з коміркою ціни",
                "verbose_name_plural": "Зв'язки меблів з комірками цін",
                "db_table": "price_parser_furniture_price_cell_mapping",
                "ordering": ["furniture__name", "sheet_row", "sheet_column"],
                "unique_together": {
                    ("furniture", "config", "sheet_row", "sheet_column")
                },
            },
        ),
        migrations.DeleteModel(
            name="FurniturePriceMapping",
        ),
    ]
