# Generated by Django 5.2 on 2025-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0011_furniturepricecellmapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesheetconfig",
            name="xlsx_file",
            field=models.FileField(
                blank=True,
                help_text="Завантажте XLSX файл з цінами (альтернатива Google таблиці)",
                null=True,
                upload_to="price_sheets/",
                verbose_name="XLSX файл",
            ),
        ),
    ]
