# Generated by Django 5.2 on 2025-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0012_add_xlsx_file_column"),
    ]

    operations = [
        # Add xlsx_file column (if not exists)
        migrations.RunSQL(
            sql="ALTER TABLE price_parser_google_sheet_config ADD COLUMN IF NOT EXISTS xlsx_file VARCHAR(100) NULL;",
            reverse_sql="ALTER TABLE price_parser_google_sheet_config DROP COLUMN IF EXISTS xlsx_file;",
        ),
        # Add price_multiplier column (if not exists)
        migrations.RunSQL(
            sql="ALTER TABLE price_parser_google_sheet_config ADD COLUMN IF NOT EXISTS price_multiplier NUMERIC(10,4) DEFAULT 1.0;",
            reverse_sql="ALTER TABLE price_parser_google_sheet_config DROP COLUMN IF EXISTS price_multiplier;",
        ),
        # Add sheet_name column (if not exists)
        migrations.RunSQL(
            sql="ALTER TABLE price_parser_google_sheet_config ADD COLUMN IF NOT EXISTS sheet_name VARCHAR(100) DEFAULT 'Sheet1';",
            reverse_sql="ALTER TABLE price_parser_google_sheet_config DROP COLUMN IF EXISTS sheet_name;",
        ),
        # Add sheet_gid column (if not exists)
        migrations.RunSQL(
            sql="ALTER TABLE price_parser_google_sheet_config ADD COLUMN IF NOT EXISTS sheet_gid VARCHAR(20) NULL;",
            reverse_sql="ALTER TABLE price_parser_google_sheet_config DROP COLUMN IF EXISTS sheet_gid;",
        ),
        # Add is_active column (if not exists)
        migrations.RunSQL(
            sql="ALTER TABLE price_parser_google_sheet_config ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;",
            reverse_sql="ALTER TABLE price_parser_google_sheet_config DROP COLUMN IF EXISTS is_active;",
        ),
        # Add created_at column (if not exists)
        migrations.RunSQL(
            sql="ALTER TABLE price_parser_google_sheet_config ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();",
            reverse_sql="ALTER TABLE price_parser_google_sheet_config DROP COLUMN IF EXISTS created_at;",
        ),
        # Add updated_at column (if not exists)
        migrations.RunSQL(
            sql="ALTER TABLE price_parser_google_sheet_config ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();",
            reverse_sql="ALTER TABLE price_parser_google_sheet_config DROP COLUMN IF EXISTS updated_at;",
        ),
    ]
