# Generated by Django 5.2 on 2025-11-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_parser', '0013_add_all_missing_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFeedConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назва для ідентифікації файлу постачальника', max_length=200, verbose_name='Назва конфігурації')),
                ('feed_url', models.URLField(help_text='Посилання на XML/YML файл (наприклад, YML для Matrolux)', verbose_name='URL фіда')),
                ('supplier', models.CharField(blank=True, help_text='Назва виробника', max_length=120, verbose_name='Постачальник')),
                ('category_hint', models.CharField(blank=True, help_text='Опишіть, для яких товарів застосовується', max_length=200, verbose_name='Категорія/нотатка')),
                ('price_multiplier', models.DecimalField(decimal_places=4, default=1.0, help_text='Наприклад, 1.0 для гривні або курс валюти', max_digits=10, verbose_name='Множник ціни')),
                ('match_by_article', models.BooleanField(default=True, help_text='Використовувати значення <model>', verbose_name='Шукати за артикулом')),
                ('match_by_name', models.BooleanField(default=True, help_text='Використовувати значення <name>, якщо артикул не знайдено', verbose_name='Шукати за назвою')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'XML фід постачальника',
                'verbose_name_plural': 'XML фіди постачальників',
                'db_table': 'price_parser_supplier_feed_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierFeedUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успішно'), ('error', 'Помилка'), ('partial', 'Частково')], max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Час початку')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Час завершення')),
                ('offers_processed', models.PositiveIntegerField(default=0, verbose_name='Оброблено оферів')),
                ('items_matched', models.PositiveIntegerField(default=0, verbose_name='Зіставлено товарів')),
                ('items_updated', models.PositiveIntegerField(default=0, verbose_name='Оновлено товарів')),
                ('errors', models.JSONField(default=list, help_text='Список помилок під час оновлення', verbose_name='Помилки')),
                ('log_details', models.TextField(blank=True, verbose_name='Деталі логу')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='price_parser.supplierfeedconfig', verbose_name='Конфігурація')),
            ],
            options={
                'verbose_name': 'Лог фіда постачальника',
                'verbose_name_plural': 'Логи фідів постачальників',
                'db_table': 'price_parser_supplier_feed_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
