# Generated by Django 5.2 on 2026-03-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0014_supplierfeedconfig_supplierfeedupdatelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierWebConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Назва для ідентифікації веб-парсера постачальника",
                        max_length=200,
                        verbose_name="Назва конфігурації",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Головна сторінка сайту постачальника",
                        verbose_name="Базовий URL магазину",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        help_text="Назва постачальника",
                        max_length=120,
                        verbose_name="Постачальник",
                    ),
                ),
                (
                    "category_hint",
                    models.CharField(
                        blank=True,
                        help_text="Пояснення для яких товарів застосовується",
                        max_length=200,
                        verbose_name="Категорія/нотатка",
                    ),
                ),
                (
                    "search_path_template",
                    models.CharField(
                        default="/?s={query}",
                        help_text="Відносний шлях для пошуку (наприклад '/?s={query}' або '/search?q={query}'). Використовується як fallback, якщо через sitemap не знайдено збіг.",
                        max_length=255,
                        verbose_name="Шаблон пошуку",
                    ),
                ),
                (
                    "crawl_from_robots",
                    models.BooleanField(
                        default=True,
                        help_text="Спробувати отримати перелік сторінок із robots.txt та sitemap.xml",
                        verbose_name="Брати URL з robots/sitemap",
                    ),
                ),
                (
                    "max_urls_to_scan",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Максимальна кількість URL зі sitemap, які будуть використані для пошуку товарів.",
                        verbose_name="Ліміт URL для аналізу",
                    ),
                ),
                (
                    "match_by_article",
                    models.BooleanField(
                        default=True,
                        help_text="Спочатку шукати відповідність за article_code",
                        verbose_name="Шукати за артикулом",
                    ),
                ),
                (
                    "match_by_name",
                    models.BooleanField(
                        default=True,
                        help_text="Якщо артикул не знайдено, шукати за назвою товару",
                        verbose_name="Шукати за назвою",
                    ),
                ),
                ("request_timeout", models.PositiveIntegerField(default=20, verbose_name="Таймаут запиту (сек)")),
                (
                    "use_selenium",
                    models.BooleanField(
                        default=False,
                        help_text="Увімкніть, якщо ціна підвантажується JavaScript-ом і не видно в HTML відповіді.",
                        verbose_name="Використовувати Selenium",
                    ),
                ),
                ("selenium_wait_seconds", models.PositiveIntegerField(default=4, verbose_name="Очікування Selenium (сек)")),
                (
                    "price_multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        help_text="Додатковий множник для конвертації валют",
                        max_digits=10,
                        verbose_name="Множник ціни",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активний")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата оновлення")),
            ],
            options={
                "verbose_name": "Веб-парсер постачальника",
                "verbose_name_plural": "Веб-парсери постачальників",
                "db_table": "price_parser_supplier_web_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierWebUpdateLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успішно"), ("error", "Помилка"), ("partial", "Частково")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, verbose_name="Час початку")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Час завершення")),
                ("items_processed", models.PositiveIntegerField(default=0, verbose_name="Перевірено товарів")),
                ("items_matched", models.PositiveIntegerField(default=0, verbose_name="Знайдено на сайті")),
                ("items_updated", models.PositiveIntegerField(default=0, verbose_name="Оновлено товарів")),
                ("errors", models.JSONField(default=list, verbose_name="Помилки")),
                ("log_details", models.TextField(blank=True, verbose_name="Деталі логу")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_logs",
                        to="price_parser.supplierwebconfig",
                        verbose_name="Конфігурація",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог веб-парсера постачальника",
                "verbose_name_plural": "Логи веб-парсерів постачальників",
                "db_table": "price_parser_supplier_web_log",
                "ordering": ["-started_at"],
            },
        ),
    ]
