# Generated by Django 5.2 on 2026-03-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_image_alter_category_name_and_more"),
        ("price_parser", "0015_supplierwebconfig_supplierwebupdatelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierwebconfig",
            name="target_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Якщо не вибрано жодної категорії, парсер оновлює всі товари.",
                related_name="supplier_web_configs",
                to="categories.category",
                verbose_name="Категорії товарів для оновлення",
            ),
        ),
    ]
