# Generated by Django 5.2 on 2026-03-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0016_supplierwebconfig_target_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierwebconfig",
            name="price_block_selector",
            field=models.CharField(
                blank=True,
                default="div.price.hp_price",
                help_text="CSS-селектор контейнера, в якому шукати ціну (наприклад: 'div.price.hp_price'). Усередині блоку застосовується правило: del=базова, ins=акційна; якщо del немає — ins як базова.",
                max_length=255,
                verbose_name="CSS селектор блоку ціни",
            ),
        ),
    ]
