# Generated by Django 5.2 on 2026-05-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0019_supplierfeedconfig_size_variant_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierfeedconfig",
            name="article_tag_name",
            field=models.CharField(
                default="model",
                help_text="Назва XML-тегу, з якого читати артикул товару. Для більшості фідів: 'model'. Для Vetro: 'article'. Для Matro: 'vendorCode'.",
                max_length=50,
                verbose_name="XML тег артикулу",
            ),
        ),
        migrations.AlterField(
            model_name="supplierfeedconfig",
            name="match_by_article",
            field=models.BooleanField(
                default=True,
                help_text="Використовувати значення з вказаного XML-тегу артикулу",
                verbose_name="Шукати за артикулом",
            ),
        ),
    ]
