# Generated by Django 5.2 on 2026-05-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0020_alter_supplierfeedconfig_article_tag_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EurosofPriceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default="1.4000",
                        help_text="На цей коефіцієнт множиться ціна з каталогу (зараз 1.4)",
                        max_digits=6,
                        verbose_name="Коефіцієнт множення",
                    ),
                ),
                (
                    "price_addon",
                    models.DecimalField(
                        decimal_places=2,
                        default="2000.00",
                        help_text="Фіксована надбавка до ціни після множення (зараз 2000)",
                        max_digits=10,
                        verbose_name="Надбавка (грн)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Останнє оновлення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Конфігурація цін Eurosof",
            },
        ),
    ]
