# Generated by Django 5.2 on 2026-07-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0032_furniture_fabric_step_raw_and_more"),
        ("price_parser", "0021_eurosofpriceconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesheetconfig",
            name="parsing_mode",
            field=models.CharField(
                choices=[
                    ("cell_mapping", "За коміркою (рядок/колонка)"),
                    ("block_structured", "Блочна структура (пошук моделі за назвою)"),
                ],
                default="cell_mapping",
                help_text="«За коміркою» — фіксовані рядок/колонка (FurniturePriceCellMapping). «Блочна структура» — пошук моделі за текстовою назвою в таблиці (FurnitureModelPriceMapping), для прайсів на кшталт «Джем», де постачальник групує моделі блоками з локальними заголовками.",
                max_length=20,
                verbose_name="Режим парсингу",
            ),
        ),
        migrations.CreateModel(
            name="FurnitureModelPriceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_label",
                    models.CharField(
                        help_text="Текст точно як у таблиці постачальника, наприклад 'Slim', 'Boston А'.",
                        max_length=200,
                        verbose_name="Назва моделі в таблиці",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        help_text="Текст заголовка цінової колонки в блоці, наприклад 'HPL покриття'.",
                        max_length=150,
                        verbose_name="Тип ціни",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активне"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_price_mappings",
                        to="price_parser.googlesheetconfig",
                        verbose_name="Конфігурація Google таблиці",
                    ),
                ),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_price_mappings",
                        to="furniture.furniture",
                        verbose_name="Меблі",
                    ),
                ),
                (
                    "size_variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Вкажіть, якщо у моделі в таблиці декілька рядків розміру. Парсер зіставляє рядок таблиці з варіантом за шириною/довжиною/висотою.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_price_mappings",
                        to="furniture.furnituresizevariant",
                        verbose_name="Розмірний варіант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зв'язок меблів з моделлю (блочний прайс)",
                "verbose_name_plural": "Зв'язки меблів з моделями (блочний прайс)",
                "db_table": "price_parser_furniture_model_price_mapping",
                "ordering": ["config", "model_label", "price_type"],
                "unique_together": {
                    ("furniture", "config", "model_label", "price_type", "size_variant")
                },
            },
        ),
    ]
