# Generated by Django 5.2 on 2026-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_parser", "0022_googlesheetconfig_parsing_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierfeedconfig",
            name="fetch_mode",
            field=models.CharField(
                choices=[
                    ("url", "Автоматично за посиланням"),
                    ("manual", "Вручну (вставити текст фіда)"),
                ],
                default="url",
                help_text="'Автоматично' — сервер сам завантажує фід за URL. 'Вручну' — якщо постачальник блокує сервер (403), перейдіть за посиланням у браузері, скопіюйте вміст і вставте його в поле нижче.",
                max_length=20,
                verbose_name="Спосіб отримання фіда",
            ),
        ),
        migrations.AddField(
            model_name="supplierfeedconfig",
            name="manual_feed_content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Використовується лише при 'Вручну'. Покрокова інструкція: 1) Перейдіть за посиланням з поля 'URL фіда' у новій вкладці. 2) Виділіть увесь вміст сторінки (Ctrl+A/Cmd+A) і скопіюйте (Ctrl+C/Cmd+C). 3) Вставте сюди (Ctrl+V/Cmd+V), повністю замінивши попередній текст. 4) Збережіть конфігурацію. 5) У списку 'Фіди постачальників' натисніть 'Тестувати парсер' або 'Оновити ціни'.",
                verbose_name="Вміст фіда (вручну)",
            ),
        ),
    ]
