# Generated by Django 5.2 on 2025-08-13 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkout", "0005_orderitem_variant_image_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liqpay_order_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID замовлення Liqpay"
                    ),
                ),
                (
                    "liqpay_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID платежу Liqpay",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сума платежу"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="UAH", max_length=3, verbose_name="Валюта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує оплати"),
                            ("success", "Успішно оплачено"),
                            ("failed", "Помилка оплати"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус платежу",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Опис платежу"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Оплачено"
                    ),
                ),
                (
                    "liqpay_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Відповідь від Liqpay"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="checkout.order",
                        verbose_name="Замовлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платіж",
                "verbose_name_plural": "Платежі",
                "ordering": ["-created_at"],
            },
        ),
    ]
