# Generated by Django 5.2 on 2025-07-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("params", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Зображення",
                    ),
                ),
                (
                    "allowed_params",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sub_categories",
                        to="params.parameter",
                        verbose_name="Дозволені параметри",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Підкатегорії",
                "verbose_name_plural": "Підкатегорії",
                "db_table": "sub_categories",
            },
        ),
    ]
