# Generated by Django 5.2 on 2025-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sub_categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="categories/",
                verbose_name="Зображення",
            ),
        ),
    ]
