# Generated by Django 5.2 on 2026-05-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sub_categories", "0002_alter_subcategory_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="allowed_params",
        ),
    ]
