# Generated by Django 5.2 on 2025-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Furniture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_promotional",
                    models.BooleanField(default=False, verbose_name="Акційний"),
                ),
                (
                    "promotional_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Акційна ціна",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="furniture/"),
                ),
            ],
            options={
                "verbose_name": "Меблі",
                "verbose_name_plural": "Меблі",
                "db_table": "furniture",
            },
        ),
    ]
