# Generated by Django 5.2 on 2025-07-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("furniture", "0001_initial"),
        ("sub_categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniture",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="furniture",
                to="sub_categories.subcategory",
            ),
        ),
    ]
