# Generated by Django 5.2 on 2025-07-09 16:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0002_initial"),
        ("sub_categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="furniture",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Меблі",
                "verbose_name_plural": "Меблі",
            },
        ),
        migrations.AddField(
            model_name="furniture",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата створення"
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="description",
            field=models.TextField(
                help_text="Детальний опис меблів", verbose_name="Опис"
            ),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="furniture/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="name",
            field=models.CharField(
                help_text="Назва меблів", max_length=200, verbose_name="Назва"
            ),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ціна",
            ),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="promotional_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ціна зі знижкою",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Акційна ціна",
            ),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Автоматично генерується з назви",
                max_length=200,
                unique=True,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="furniture",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="furniture",
                to="sub_categories.subcategory",
                verbose_name="Підкатегорія",
            ),
        ),
    ]
