# Generated by Django 5.2 on 2025-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0003_alter_furniture_options_furniture_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furniture",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата створення"
            ),
        ),
    ]
