# Generated by Django 5.2 on 2025-08-01 06:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0006_add_fabric_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnitureSizeVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Висота меблів у сантиметрах",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Висота (см)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ширина меблів у сантиметрах",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ширина (см)",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Довжина меблів у сантиметрах",
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Довжина (см)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ціна для цього розміру",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_variants",
                        to="furniture.furniture",
                        verbose_name="Меблі",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розмірний варіант меблів",
                "verbose_name_plural": "Розмірні варіанти меблів",
                "db_table": "furniture_size_variants",
                "ordering": ["height", "width", "length"],
            },
        ),
    ]
