# Generated by Django 5.2 on 2025-08-11 06:56

from django.db import migrations, models


def generate_article_codes(apps, schema_editor):
    """Generate unique article codes for existing furniture items."""
    Furniture = apps.get_model('furniture', 'Furniture')
    for i, furniture in enumerate(Furniture.objects.all(), 1):
        furniture.article_code = f"FUR{i:04d}"
        furniture.save()


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0007_furnituresizevariant"),
    ]

    operations = [
        # Add stock_status field
        migrations.AddField(
            model_name='furniture',
            name='stock_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('in_stock', 'На складі'),
                    ('on_order', 'Під замовлення'),
                ],
                default='in_stock',
                verbose_name="Статус наявності",
                help_text="Чи є товар на складі або під замовлення"
            ),
        ),
        # Add article_code field without unique constraint first
        migrations.AddField(
            model_name='furniture',
            name='article_code',
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="Код товару",
                help_text="Унікальний код товару"
            ),
        ),
        # Generate article codes for existing items
        migrations.RunPython(generate_article_codes),
        # Make article_code not null
        migrations.AlterField(
            model_name='furniture',
            name='article_code',
            field=models.CharField(
                max_length=50,
                verbose_name="Код товару",
                help_text="Унікальний код товару"
            ),
        ),
        # Add unique constraint
        migrations.AlterField(
            model_name='furniture',
            name='article_code',
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name="Код товару",
                help_text="Унікальний код товару"
            ),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name='furniture',
            index=models.Index(fields=['article_code'], name='furniture_article_code_idx'),
        ),
        migrations.AddIndex(
            model_name='furniture',
            index=models.Index(fields=['stock_status'], name='furniture_stock_status_idx'),
        ),
    ]
