# Generated by Django 5.2 on 2025-08-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0009_auto_20250811_0956"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="furniture",
            new_name="furniture_article_62d850_idx",
            old_name="furniture_article_code_idx",
        ),
        migrations.RenameIndex(
            model_name="furniture",
            new_name="furniture_stock_s_b4c5c4_idx",
            old_name="furniture_stock_status_idx",
        ),
    ]
