# Generated by Django 5.2 on 2025-08-11 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "furniture",
            "0010_rename_furniture_article_code_idx_furniture_article_62d850_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="furnituresizevariant",
            name="height",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Висота меблів у сантиметрах",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Висота (см)",
            ),
        ),
        migrations.AlterField(
            model_name="furnituresizevariant",
            name="length",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Довжина меблів у сантиметрах",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Довжина (см)",
            ),
        ),
        migrations.AlterField(
            model_name="furnituresizevariant",
            name="width",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Ширина меблів у сантиметрах",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Ширина (см)",
            ),
        ),
    ]
