# Generated by Django 5.2 on 2025-08-11 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0011_alter_furnituresizevariant_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnitureImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="furniture/", verbose_name="Зображення"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Альтернативний текст"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок відображення"
                    ),
                ),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="furniture.furniture",
                        verbose_name="Меблі",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зображення меблів",
                "verbose_name_plural": "Зображення меблів",
                "db_table": "furniture_images",
                "ordering": ["position", "id"],
            },
        ),
    ]
