# Generated by Django 5.2 on 2025-08-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0012_furnitureimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnitureVariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Назва варіанту (наприклад: 'Білий', 'Дуб світлий')",
                        max_length=100,
                        verbose_name="Назва варіанту",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Зображення меблів у цьому варіанті",
                        upload_to="furniture/variants/",
                        verbose_name="Зображення варіанту",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Посилання на варіант (опціонально)",
                        verbose_name="Посилання",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Цей варіант буде показаний першим",
                        verbose_name="Варіант за замовчуванням",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок відображення"
                    ),
                ),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_images",
                        to="furniture.furniture",
                        verbose_name="Меблі",
                    ),
                ),
            ],
            options={
                "verbose_name": "Варіант зображення меблів",
                "verbose_name_plural": "Варіанти зображень меблів",
                "db_table": "furniture_variant_images",
                "ordering": ["position", "name"],
                "unique_together": {("furniture", "name")},
            },
        ),
    ]
