# Generated by Django 5.2 on 2025-08-11 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0013_furniturevariantimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="furnituresizevariant",
            name="is_foldable",
            field=models.BooleanField(
                default=False,
                help_text="Чи можуть меблі складатися",
                verbose_name="Складні меблі",
            ),
        ),
        migrations.AddField(
            model_name="furnituresizevariant",
            name="unfolded_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Довжина меблів у розгорнутому стані",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Довжина розгорнута (см)",
            ),
        ),
        migrations.AlterField(
            model_name="furnituresizevariant",
            name="length",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Довжина меблів у сантиметрах (складена)",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Довжина (см)",
            ),
        ),
    ]
