# Generated by Django 5.2 on 2025-08-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0014_furnituresizevariant_is_foldable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniture",
            name="sale_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Коли закінчується акційна пропозиція",
                null=True,
                verbose_name="Дата закінчення акції",
            ),
        ),
    ]
