# Generated by Django 5.2 on 2025-08-22 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0015_furniture_sale_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="furnituresizevariant",
            name="promotional_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Акційна ціна для цього розміру (залиште порожнім для використання основної акційної ціни)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Акційна ціна",
            ),
        ),
    ]
