# Generated by Django 5.2 on 2025-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0016_furnituresizevariant_promotional_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="furnituresizevariant",
            name="is_promotional",
            field=models.BooleanField(
                default=False,
                help_text="Чи є цей розмір акційним незалежно від основного товару",
                verbose_name="Акційний розмір",
            ),
        ),
        migrations.AddField(
            model_name="furnituresizevariant",
            name="sale_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Коли закінчується акційна пропозиція для цього розміру",
                null=True,
                verbose_name="Дата закінчення акції розміру",
            ),
        ),
    ]
