# Generated by Django 5.2 on 2025-09-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0017_furnituresizevariant_is_promotional_and_more'),
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnituresizevariant',
            name='parameter',
            field=models.ForeignKey(blank=True, help_text='Параметр підкатегорії, який змінюється для цього розміру', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_variants', to='params.parameter', verbose_name='Параметр'),
        ),
        migrations.AddField(
            model_name='furnituresizevariant',
            name='parameter_value',
            field=models.CharField(blank=True, help_text='Відображатиметься замість основного значення параметра при виборі цього розміру', max_length=200, verbose_name='Значення параметра'),
        ),
    ]
