# Generated by Django 5.2 on 2025-10-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0019_alter_furniturevariantimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturevariantimage',
            name='stock_status',
            field=models.CharField(choices=[('in_stock', 'На складі'), ('on_order', 'Під замовлення')], default='in_stock', help_text='Використовується для відображення статусу при виборі цього варіанту', max_length=20, verbose_name='Статус наявності'),
        ),
    ]
