# Generated by Django 5.2 on 2025-10-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0020_furniturevariantimage_stock_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniture",
            name="custom_option_name",
            field=models.CharField(
                blank=True,
                help_text="Назва параметра для власних варіантів вибору (наприклад, 'Комплектація').",
                max_length=200,
                verbose_name="Назва додаткового параметра",
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="custom_option_values",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список варіантів вибору для додаткового параметра.",
                verbose_name="Варіанти додаткового параметра",
            ),
        ),
    ]
