# Generated by Django 5.2 on 2025-10-22 18:45

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_options(apps, schema_editor):
    Furniture = apps.get_model("furniture", "Furniture")
    FurnitureCustomOption = apps.get_model("furniture", "FurnitureCustomOption")

    for furniture in Furniture.objects.all():
        values = getattr(furniture, "custom_option_values", None)
        if not values:
            continue
        if isinstance(values, str):
            # If stored as JSON string, try to split by newline
            raw_values = [v.strip() for v in values.splitlines() if v.strip()]
        else:
            raw_values = list(values)

        for position, value in enumerate(raw_values):
            FurnitureCustomOption.objects.create(
                furniture=furniture,
                value=value,
                position=position,
                is_active=True,
            )


def backwards_copy_options(apps, schema_editor):
    Furniture = apps.get_model("furniture", "Furniture")
    FurnitureCustomOption = apps.get_model("furniture", "FurnitureCustomOption")

    for furniture in Furniture.objects.all():
        options = (
            FurnitureCustomOption.objects.filter(furniture=furniture)
            .order_by("position", "id")
            .values_list("value", flat=True)
        )
        furniture.custom_option_values = list(options)
        furniture.save(update_fields=["custom_option_values"])


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0021_furniture_custom_option_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnitureCustomOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Варіант вибору для додаткового параметра.",
                        max_length=200,
                        verbose_name="Значення",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок відображення варіантів.",
                        verbose_name="Позиція",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Приховати варіант без видалення.",
                        verbose_name="Активний",
                    ),
                ),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_options",
                        to="furniture.furniture",
                        verbose_name="Меблі",
                    ),
                ),
            ],
            options={
                "verbose_name": "Варіант додаткового параметра",
                "verbose_name_plural": "Варіанти додаткового параметра",
                "db_table": "furniture_custom_options",
                "ordering": ["position", "id"],
            },
        ),
        migrations.RunPython(forwards_copy_options, backwards_copy_options),
        migrations.RemoveField(
            model_name="furniture",
            name="custom_option_values",
        ),
    ]
