# Generated by Django 5.2 on 2025-10-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0022_furniturecustomoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniturecustomoption",
            name="price_delta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Сума, що додається до базової ціни при виборі цього варіанту.",
                max_digits=10,
                verbose_name="Надбавка до ціни",
            ),
        ),
    ]
