# Generated by Django 5.2 on 2025-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0023_furniturecustomoption_price_delta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furniture",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="furniture/",
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureimage",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to="furniture/", verbose_name="Зображення"
            ),
        ),
        migrations.AlterField(
            model_name="furniturevariantimage",
            name="image",
            field=models.ImageField(
                help_text="Зображення меблів у цьому варіанті",
                max_length=255,
                upload_to="furniture/variants/",
                verbose_name="Зображення варіанту",
            ),
        ),
    ]
