# Generated by Django 5.2 on 2025-11-10 15:05

import utils.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0024_alter_furniture_image_alter_furnitureimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="furniture",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=utils.media_paths.furniture_main_image_upload_to,
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="furnitureimage",
            name="image",
            field=models.ImageField(
                max_length=255,
                upload_to=utils.media_paths.furniture_gallery_image_upload_to,
                verbose_name="Зображення",
            ),
        ),
        migrations.AlterField(
            model_name="furniturevariantimage",
            name="image",
            field=models.ImageField(
                help_text="Зображення меблів у цьому варіанті",
                max_length=255,
                upload_to=utils.media_paths.furniture_variant_image_upload_to,
                verbose_name="Зображення варіанту",
            ),
        ),
    ]
