# Generated by Django 5.2 on 2025-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_category', '0002_fabriccolorpalette_fabriccolor'),
        ('furniture', '0025_alter_furniture_image_alter_furnitureimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='color_palettes',
            field=models.ManyToManyField(blank=True, help_text='Набори кольорів оббивки, що доступні для товару.', related_name='furniture_items', to='fabric_category.fabriccolorpalette', verbose_name='Палітри покриттів'),
        ),
    ]
