# Generated by Django 5.2 on 2026-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0026_furniture_color_palettes"),
    ]

    operations = [
        migrations.AddField(
            model_name="furnituresizevariant",
            name="vendor_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="vendorCode з фіду постачальника для цього розміру (використовується для автооновлення цін)",
                max_length=50,
                verbose_name="Код постачальника",
            ),
        ),
    ]
