# Generated by Django 5.2 on 2026-04-25 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0027_furnituresizevariant_vendor_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[],
            options={
                "verbose_name": "Ліжко",
                "verbose_name_plural": "Ліжка",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("furniture.furniture",),
        ),
        migrations.CreateModel(
            name="BedSizeVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sleeping_width",
                    models.PositiveIntegerField(
                        help_text="Наприклад: 80, 90, 120, 140, 160, 180, 200",
                        verbose_name="Ширина спального місця (см)",
                    ),
                ),
                (
                    "sleeping_length",
                    models.PositiveIntegerField(
                        help_text="Наприклад: 190, 200",
                        verbose_name="Довжина спального місця (см)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "promotional_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Акційна ціна",
                    ),
                ),
                (
                    "is_promotional",
                    models.BooleanField(default=False, verbose_name="Акційний розмір"),
                ),
                (
                    "sale_end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата закінчення акції"
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="vendorCode з фіду постачальника (для автооновлення цін)",
                        max_length=50,
                        verbose_name="Код постачальника",
                    ),
                ),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bed_size_variants",
                        to="furniture.furniture",
                        verbose_name="Ліжко",
                    ),
                ),
            ],
            options={
                "verbose_name": "Розмірний варіант ліжка",
                "verbose_name_plural": "Розмірні варіанти ліжок",
                "db_table": "furniture_bed_size_variants",
                "ordering": ["sleeping_width", "sleeping_length"],
                "unique_together": {("furniture", "sleeping_width", "sleeping_length")},
            },
        ),
    ]
