# Generated by Django 5.2 on 2026-04-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0029_delete_bedsizevariant"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniture",
            name="variant_group_leader",
            field=models.ForeignKey(
                blank=True,
                help_text="Вкажіть базову модель, якщо цей товар є варіантом (колір/модифікація). Базова модель залишає це поле порожнім.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="color_variants",
                to="furniture.furniture",
                verbose_name="Базова модель",
            ),
        ),
        migrations.AddField(
            model_name="furniture",
            name="variant_label",
            field=models.CharField(
                blank=True,
                help_text="Коротка мітка для чіпу варіанту (напр. BLACK, KHAKI, 645-1B BLACK). Якщо порожнє — береться суфікс назви.",
                max_length=100,
                verbose_name="Мітка варіанту",
            ),
        ),
    ]
