# Generated by Django 5.2 on 2026-04-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0030_add_variant_group_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniture",
            name="base_model_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Однакове значення = один варіантний ряд. Порожнє — товар самостійний.",
                max_length=200,
                verbose_name="Назва базової моделі",
            ),
        ),
    ]
