# Generated by Django 5.2 on 2026-05-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("furniture", "0031_add_base_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="furniture",
            name="fabric_step_raw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Різниця між Економ і -1КАТ до формули (для перерахунку цін)",
                max_digits=10,
                null=True,
                verbose_name="Крок тканини (сировина)",
            ),
        ),
        migrations.AddField(
            model_name="furnituresizevariant",
            name="catalog_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Оригінальна ціна з прайс-листа постачальника (до формули)",
                max_digits=10,
                null=True,
                verbose_name="Ціна каталогу (сировина)",
            ),
        ),
    ]
