"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ["SECRET_KEY"]
except KeyError:
    raise RuntimeError(
        "The SECRET_KEY environment variable is not set. Please set it to a secure value."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
INTERNAL_IPS = ["127.0.0.1"]


CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "http://127.0.0.1:8000,http://localhost:8000").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    # Local apps
    "custom_admin.apps.CustomAdminConfig",
    "shop.apps.ShopConfig",
    "categories.apps.CategoriesConfig",
    "furniture.apps.FurnitureConfig",
    "sub_categories.apps.SubCategoriesConfig",
    "params.apps.ParamConfig",
    "checkout.apps.CheckoutConfig",
    "delivery.apps.DeliveryConfig",
    "fabric_category.apps.FabricCategoryConfig",
    "price_parser.apps.PriceParserConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "store.middleware.ConnectionResilienceMiddleware",  # Connection resilience
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "store.middleware.PostRequestResilienceMiddleware",  # POST request resilience
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "store.middleware.AdminConnectionMonitorMiddleware",  # Admin connection monitoring
]

ROOT_URLCONF = "store.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "shop.context_processors.cart_count",
                "shop.context_processors.breadcrumbs",
                "shop.context_processors.seo_defaults",
                "shop.context_processors.seasonal_pack",
            ],
        },
    },
]

WSGI_APPLICATION = "store.wsgi.application"

# --- SEO / Site settings ---
SITE_DOMAIN = os.getenv("SITE_DOMAIN", "montal.com.ua")
SITE_BASE_URL = os.getenv("SITE_BASE_URL", f"https://{SITE_DOMAIN}")
GOOGLE_SITE_VERIFICATION = os.getenv("GOOGLE_SITE_VERIFICATION", "")

# --- Third-party integrations ---
SALESDRIVE_API_KEY = os.getenv("SALASEDRIVE_API", "")
SALESDRIVE_API_ENDPOINT = os.getenv(
    "SALESDRIVE_API_ENDPOINT", "https://montal.salesdrive.me/handler/"
)

# --- Invoice configuration ---
INVOICE_COMPANY_NAME = os.getenv("INVOICE_COMPANY_NAME", "ФОП Кивенко Анастасія Олегівна")
INVOICE_COMPANY_ADDRESS = os.getenv("INVOICE_COMPANY_ADDRESS", "м. Дніпро, проспект Богдана Хмельницького, 31Д")
INVOICE_COMPANY_PHONE = os.getenv("INVOICE_COMPANY_PHONE", "+380678416272")
INVOICE_COMPANY_EMAIL = os.getenv("INVOICE_COMPANY_EMAIL", "info@montal.com.ua")
INVOICE_IBAN = os.getenv("INVOICE_IBAN", "UA313000010000000000031300001")
INVOICE_EDRPOU = os.getenv("INVOICE_EDRPOU", "678416272")
INVOICE_FONT_PATH = os.getenv("INVOICE_FONT_PATH", "/System/Library/Fonts/Supplemental/Arial.ttf")
INVOICE_LOGO_URL = os.getenv("INVOICE_LOGO_URL", "/Users/anastasia/cursor repo/Montal_Home/static/images/logo.jpg")
INVOICE_PAYMENT_TERMS_DAYS = int(os.getenv("INVOICE_PAYMENT_TERMS_DAYS", "3"))


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("PGDATABASE"),
        "USER": os.environ.get("PGUSER"),
        "PASSWORD": os.environ.get("PGPASSWORD"),
        "HOST": os.environ.get("PGHOST"),
        "PORT": os.environ.get("PGPORT", "5432"),
        # Connection optimization settings
        "CONN_MAX_AGE": 300,  # Keep connections alive for 5 minutes
        "CONN_HEALTH_CHECKS": True,  # Enable connection health checks
        "OPTIONS": {
            "connect_timeout": 10,  # Connection timeout in seconds
            "application_name": "montal_home",
        }
    }
}

# Use PostgreSQL in production with enhanced connection settings
if os.getenv("DATABASE_URL"):
    import dj_database_url
    db_config = dj_database_url.parse(
        os.environ["DATABASE_URL"],
        conn_max_age=300,  # Increased from 60 to 300 seconds
        ssl_require=True
    )
    # Add additional connection options for production
    db_config["OPTIONS"] = {
        "connect_timeout": 10,
        "application_name": "montal_home_prod",
    }
    DATABASES["default"] = db_config


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Authentication redirects
LOGIN_URL = "custom_admin:login"
LOGIN_REDIRECT_URL = "custom_admin:dashboard"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "uk"  # Changed to Ukrainian for better localization

TIME_ZONE = "Europe/Kyiv"  # Updated to modern IANA timezone identifier

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# --- Статика (WhiteNoise) ---
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [ BASE_DIR / "static" ]

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# --- Медіа в Cloudinary ---
# INSTALLED_APPS += ["cloudinary", "cloudinary_storage"]
# STORAGES = {
#     "default": {  # усі FileField/ImageField -> йдуть сюди
#         "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
#     },
#     "staticfiles": {  # статика віддається WhiteNoise
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }
# # DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
# # Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


# --- Медіа у Cloudflare R2 з віддачею через BunnyCDN ---
INSTALLED_APPS += ["storages"]

# 1) Базовий CDN-домен (твій CNAME на Bunny): https://cdn.example.com/
MEDIA_URL = os.getenv("MEDIA_URL", "https://cdn.montal.com.ua/")


AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")  # напр. https://<accountid>.r2.cloudflarestorage.com
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")

# Для R2 region зазвичай "auto"
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto")

# R2 добре працює з virtual-hosted style
AWS_S3_ADDRESSING_STYLE = "virtual"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# ------------------

# Responsive image generation defaults
IMAGE_VARIANT_WIDTHS = [400, 800, 1200]
IMAGE_VARIANT_FORMAT = os.getenv("IMAGE_VARIANT_FORMAT", "webp")
IMAGE_VARIANT_QUALITY = int(os.getenv("IMAGE_VARIANT_QUALITY", "82"))
IMAGE_VARIANT_DEFAULT_WIDTH = int(os.getenv("IMAGE_VARIANT_DEFAULT_WIDTH", "800"))
IMAGE_VARIANT_SIZES_ATTR = os.getenv(
    "IMAGE_VARIANT_SIZES_ATTR",
    "(max-width: 640px) 400px, (max-width: 1024px) 800px, 1200px",
)
IMAGE_VARIANT_ASSUME_EXISTS = os.getenv("IMAGE_VARIANT_ASSUME_EXISTS", "true").lower() == "true"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Security settings
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

# Session settings with enhanced resilience
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request for better persistence
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF settings with enhanced security
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = True  # Store CSRF token in session for better reliability

# Enhanced cache settings with fallback
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
        "TIMEOUT": 300,  # 5 minutes default timeout
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
            "CULL_FREQUENCY": 3,
        }
    },
    # Fallback cache for critical operations
    "fallback": {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
    }
}

# Enhanced logging configuration for connection monitoring
# Production-friendly logging (console only for Heroku)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.db.backends": {
            "handlers": ["console"],
            "level": "WARNING",  # Log database connection issues
            "propagate": False,
        },
        "django.db": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "store.connection": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Add file logging only in development
if DEBUG and not os.getenv("DATABASE_URL"):
    # Create logs directory if it doesn't exist (development only)
    logs_dir = BASE_DIR / "logs"
    logs_dir.mkdir(exist_ok=True)
    
    # Only add file logging in development when not using DATABASE_URL (production)
    LOGGING["handlers"]["file"] = {
        "class": "logging.FileHandler",
        "filename": logs_dir / "django.log",
        "formatter": "verbose",
    }
    
    # Add file handler to all loggers in development
    for logger_name in LOGGING["loggers"]:
        LOGGING["loggers"][logger_name]["handlers"].append("file")
    LOGGING["root"]["handlers"].append("file")

# Application-specific settings
FURNITURE_PARAM_LABELS = {
    "width": "Ширина (см)",
    "height": "Висота (см)",
    "depth": "Глибина (см)",
    "color": "Колір",
    "material_coating": "Матеріал покриття",
    "material_frame": "Матеріал каркасу",
    "manufacture": "Країна виробник",
    "length": "Довжина (см)",
    "max_length": "Максимальна довжина (см)",
    "tabletop material": "Матеріал стільниці",
    "table_type": "Тип",
    "layout mechanism": "Механізм розкладки",
    "form": "Форма",
    "berth": "Спальне місце",
    "lifting_mechanism": "Під'ємний механізм",
    "chair_type": "Тип крісла",
    "max_weight": "Максимальне навантаження (кг)",
    "headrest": "Підголовник",
    "adjustment": "Регулювання",
    "warranty": "Гарантія",
    "furniture_type": "М'які меблі",
    "filler_type": "Тип наповнювача",
    "armrest": "Підлокітники",
    "hardness_level": "Рівень жорсткості",
    "mattress_height": "Висота матрацу (см)",
}

# API Keys and external services
NOVA_POSHTA_API_KEY = os.getenv("NOVA_POSHTA_API_KEY")
CARGO_WAREHOUSE_REF = "9a68df70-0267-42a8-bb5c-37f427e36ee4"

# Pagination settings
ITEMS_PER_PAGE = 9

# Connection resilience and retry settings
CONNECTION_RESILIENCE = {
    "MAX_RETRIES": 3,
    "RETRY_DELAY": 1,  # seconds
    "EXPONENTIAL_BACKOFF": True,
    "CIRCUIT_BREAKER_THRESHOLD": 5,  # failures before circuit opens
    "CIRCUIT_BREAKER_TIMEOUT": 60,  # seconds before trying again
}

# Admin panel specific settings for graceful reconnects
ADMIN_CONNECTION_SETTINGS = {
    "ENABLE_AUTO_RECONNECT": True,
    "CONNECTION_TIMEOUT": 30,  # seconds
    "RETRY_ATTEMPTS": 3,
    "FALLBACK_MODE": True,  # Enable fallback for critical operations
}

# POST request resilience settings
POST_REQUEST_RESILIENCE = {
    "ENABLE_RETRY": True,
    "MAX_RETRIES": 2,
    "RETRY_DELAY": 0.5,  # seconds
    "SAVE_DRAFT_ON_FAILURE": True,  # Save form data on connection failure
}
