# Generated by Django 5.2 on 2025-07-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("furniture", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Параметр",
                "verbose_name_plural": "Параметри",
                "db_table": "parameters",
            },
        ),
        migrations.CreateModel(
            name="FurnitureParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=200)),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="furniture.furniture",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="furniture_parameters",
                        to="params.parameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Параметр меблів",
                "verbose_name_plural": "Параметри меблів",
                "db_table": "furniture_parameters",
                "unique_together": {("furniture", "parameter")},
            },
        ),
    ]
