# Generated by Django 5.2 on 2025-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("customer_last_name", models.CharField(max_length=200)),
                (
                    "customer_phone_number",
                    models.CharField(max_length=10, verbose_name="Номер телефону"),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "delivery_city",
                    models.CharField(max_length=100, verbose_name="Місто доставки"),
                ),
                (
                    "delivery_branch",
                    models.CharField(
                        max_length=200, verbose_name="Відділення Нової Пошти"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна"
                    ),
                ),
            ],
            options={
                "verbose_name": "Елемент замовлення",
                "verbose_name_plural": "Елементи замовлення",
            },
        ),
    ]
