# Generated by Django 5.2 on 2025-07-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkout", "0001_initial"),
        ("furniture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="furniture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="furniture.furniture"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="checkout.order"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                through="checkout.OrderItem", to="furniture.furniture"
            ),
        ),
    ]
