# Generated by Django 5.2 on 2025-08-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_order_delivery_address_order_delivery_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="fabric_category_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID категорії тканини"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_variant_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID розмірного варіанту"
            ),
        ),
    ]
