# Generated by Django 5.2 on 2025-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_orderitem_fabric_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant_image_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID варіанту зображення"
            ),
        ),
    ]
