# Generated by Django 5.2 on 2025-08-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_orderitem_variant_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_promotional",
            field=models.BooleanField(default=False, verbose_name="Акційний товар"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Оригінальна ціна",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_variant_is_promotional",
            field=models.BooleanField(
                default=False, verbose_name="Акційний розмірний варіант"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_variant_original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Оригінальна ціна розмірного варіанту",
            ),
        ),
    ]
