# Generated by Django 5.2 on 2025-10-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0006_orderitem_is_promotional_orderitem_original_price_and_more"),
        ("furniture", "0022_furniturecustomoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="custom_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="furniture.furniturecustomoption",
                verbose_name="Обраний варіант параметра",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_option_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Назва додаткового параметра"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_option_value",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="Значення додаткового параметра",
            ),
        ),
    ]
