# Generated by Django 5.2 on 2025-10-22 15:50

import django.db.models.deletion
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0006_orderitem_is_promotional_orderitem_original_price_and_more"),
        ("furniture", "0023_furniturecustomoption_price_delta"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE checkout_orderitem
                        ADD COLUMN IF NOT EXISTS custom_option_id bigint;
                    """,
                    reverse_sql="""
                        ALTER TABLE checkout_orderitem
                        DROP COLUMN IF EXISTS custom_option_id;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE checkout_orderitem
                        ADD COLUMN IF NOT EXISTS custom_option_name varchar(200) NOT NULL DEFAULT '';
                    """,
                    reverse_sql="""
                        ALTER TABLE checkout_orderitem
                        DROP COLUMN IF EXISTS custom_option_name;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE checkout_orderitem
                        ALTER COLUMN custom_option_name DROP DEFAULT;
                    """,
                    reverse_sql="""
                        ALTER TABLE checkout_orderitem
                        ALTER COLUMN custom_option_name SET DEFAULT '';
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE checkout_orderitem
                        ADD COLUMN IF NOT EXISTS custom_option_value varchar(200) NOT NULL DEFAULT '';
                    """,
                    reverse_sql="""
                        ALTER TABLE checkout_orderitem
                        DROP COLUMN IF EXISTS custom_option_value;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE checkout_orderitem
                        ALTER COLUMN custom_option_value DROP DEFAULT;
                    """,
                    reverse_sql="""
                        ALTER TABLE checkout_orderitem
                        ALTER COLUMN custom_option_value SET DEFAULT '';
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE checkout_orderitem
                        ADD COLUMN IF NOT EXISTS custom_option_price numeric(10, 2);
                    """,
                    reverse_sql="""
                        ALTER TABLE checkout_orderitem
                        DROP COLUMN IF EXISTS custom_option_price;
                    """,
                ),
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1
                                FROM information_schema.table_constraints
                                WHERE constraint_name = 'checkout_orderitem_custom_option_id_fk'
                                    AND table_name = 'checkout_orderitem'
                            ) THEN
                                ALTER TABLE checkout_orderitem
                                ADD CONSTRAINT checkout_orderitem_custom_option_id_fk
                                FOREIGN KEY (custom_option_id)
                                REFERENCES furniture_custom_options (id)
                                DEFERRABLE INITIALLY DEFERRED;
                            END IF;
                        END;
                        $$;
                    """,
                    reverse_sql="""
                        ALTER TABLE checkout_orderitem
                        DROP CONSTRAINT IF EXISTS checkout_orderitem_custom_option_id_fk;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="orderitem",
                    name="custom_option",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="furniture.furniturecustomoption",
                        verbose_name="Обраний варіант параметра",
                    ),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="custom_option_name",
                    field=models.CharField(
                        blank=True, max_length=200, verbose_name="Назва додаткового параметра"
                    ),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="custom_option_value",
                    field=models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Значення додаткового параметра",
                    ),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="custom_option_price",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Надбавка за параметр",
                    ),
                ),
            ],
        ),
    ]
