# Generated by Django 5.2 on 2025-10-22 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_orderitem_custom_option_orderitem_custom_option_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_message',
            field=models.TextField(blank=True, help_text='Додається до листа при надсиланні реквізитів', verbose_name='Повідомлення клієнту'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_instructions_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/instructions/', verbose_name='Файл з реквізитами для оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_link',
            field=models.URLField(blank=True, verbose_name='Посилання на оплату'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_note',
            field=models.TextField(blank=True, help_text='Внутрішні примітки щодо замовлення', verbose_name='Нотатка менеджера'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Обробляється'), ('awaiting_payment', 'Очікує оплату'), ('confirmed', 'Підтверджено'), ('shipping', 'Доставка'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='processing', max_length=30, verbose_name='Статус замовлення'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оновлення статусу'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Обробляється'), ('awaiting_payment', 'Очікує оплату'), ('confirmed', 'Підтверджено'), ('shipping', 'Доставка'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], max_length=30, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='checkout.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Історія статусу замовлення',
                'verbose_name_plural': 'Історії статусів замовлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
