# Generated by Django 5.2 on 2025-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "checkout",
            "0007_orderitem_custom_option_orderitem_custom_option_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата генерації рахунку"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_pdf_path",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Шлях до файлу рахунку"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_pdf_url",
            field=models.URLField(blank=True, verbose_name="Посилання на рахунок"),
        ),
        migrations.AddField(
            model_name="order",
            name="is_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Після підтвердження автоматично генерується рахунок-фактура.",
                verbose_name="Підтверджено",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("local", "Доставка по місту"), ("nova_poshta", "Нова Пошта")],
                max_length=20,
                verbose_name="Тип доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("iban", "IBAN")], max_length=20, verbose_name="Тип оплати"
            ),
        ),
    ]
