# Generated by Django 5.2 on 2025-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0008_order_invoice_generated_at_order_invoice_pdf_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoice_pdf_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Посилання на рахунок"
            ),
        ),
    ]
