# Generated by Django 5.2 on 2025-11-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0011_orderstatus_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("iban", "IBAN"), ("liqpay", "LiqPay")],
                max_length=20,
                verbose_name="Тип оплати",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="checkout.orderstatus",
                verbose_name="Статус замовлення",
            ),
        ),
    ]
