# Generated by Django 5.2 on 2025-11-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_order_iban_invoice_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, verbose_name='HEX код кольору'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID кольору палітри'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_image_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL зразка кольору'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Назва кольору'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_palette_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Назва палітри кольорів'),
        ),
    ]
