# Generated by Django 5.2 on 2025-11-06 15:55

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    SeasonalSettings = apps.get_model("shop", "SeasonalSettings")
    SeasonalSettings.objects.get_or_create(pk=1, defaults={"is_enabled": True})


def remove_default_settings(apps, schema_editor):
    SeasonalSettings = apps.get_model("shop", "SeasonalSettings")
    SeasonalSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_furniture_category_remove_orderitem_furniture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Якщо вимкнено, гірлянда та сніг на сайті не відображатимуться.', verbose_name='Увімкнути святкове оформлення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Сезонне оформлення',
                'verbose_name_plural': 'Сезонне оформлення',
            },
        ),
        migrations.RunPython(create_default_settings, remove_default_settings),
    ]
