# Generated by Django 5.2 on 2025-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_seasonalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalsettings',
            name='name',
            field=models.CharField(default='Зимовий пак', help_text='Назва поточного набору святкових елементів.', max_length=120, verbose_name='Назва сезонного паку'),
        ),
    ]
