# Generated by Django 5.2 on 2025-11-15 10:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_palettes', to='fabric_category.fabricbrand')),
            ],
            options={
                'verbose_name': 'Палітра покриттів',
                'verbose_name_plural': 'Палітри покриттів',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('hex_code', models.CharField(help_text='Колір у форматі #RRGGBB', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='fabric_category.fabriccolorpalette')),
            ],
            options={
                'verbose_name': 'Колір палітри',
                'verbose_name_plural': 'Кольори палітр',
                'ordering': ('palette', 'position', 'id'),
                'unique_together': {('palette', 'name')},
            },
        ),
    ]
