# Generated by Django 5.2 on 2025-11-15 10:55

import utils.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_category', '0002_fabriccolorpalette_fabriccolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabriccolor',
            name='image',
            field=models.ImageField(blank=True, help_text='Зображення зразка тканини/покриття.', max_length=255, null=True, upload_to=utils.media_paths.fabric_color_image_upload_to, verbose_name='Зразок покриття'),
        ),
    ]
