# Generated by Django 5.2 on 2025-11-15 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_category', '0003_fabriccolor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabriccolor',
            name='hex_code',
            field=models.CharField(blank=True, help_text='Колір у форматі #RRGGBB', max_length=7, validators=[django.core.validators.RegexValidator(message='Вкажіть колір у форматі #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
