# Generated by Django 5.2 on 2026-07-20 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogUpdateJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        choices=[
                            ("evrodim", "Evrodim"),
                            ("andersen", "Andersen"),
                            ("kreslalux", "Kreslalux"),
                            ("eurosof", "Eurosof"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("import", "Імпорт нових товарів"),
                            ("update_prices", "Оновлення цін"),
                            ("update_params", "Оновлення характеристик"),
                        ],
                        max_length=20,
                    ),
                ),
                ("catalog_key", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Виконується"),
                            ("success", "Успішно"),
                            ("error", "Помилка"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
