# Generated by Django 5.2 on 2026-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_admin", "0002_alter_catalogupdatejob_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogupdatejob",
            name="supplier",
            field=models.CharField(
                choices=[
                    ("evrodim", "Evrodim"),
                    ("andersen", "Andersen"),
                    ("kreslalux", "Kreslalux"),
                    ("eurosof", "Eurosof"),
                    ("divanoff", "Divanoff"),
                    ("google_sheet", "Google Sheets"),
                    ("supplier_feed", "XML/YML фід"),
                    ("supplier_web", "Веб-скрапінг"),
                ],
                max_length=20,
            ),
        ),
    ]
